### ISSUE TITLE
unnecessary Console Log in index file

### ISSUE THREAD

**Issue by pradip-kher** [Mood-al/react-tabs-scrollable#1]
can you remove this two log from index.js file  
console.log(tabsClassName)
  console.log(tabsContainerClassName)

**Comment by Mood-al** [comment]
Of course , do you suggest any other changes on the component?

**Comment by IbnDaanis** [comment]
When will this be fixed?

**Comment by Mood-al** [comment]
> When will this be fixed?

On this weekend hopefully

**Comment by Mood-al** [comment]
done, please update to the latest version
