### ISSUE TITLE
Arrow buttons are causing a form to submit with HTML 

### ISSUE THREAD

**Issue by ahmedatadjust** [Mood-al/react-tabs-scrollable#10]
Hello, 

I have a use-case where I am using the tabs inside form. When the arrow button is clicked it submits the form. If we add `type="button"` to arrow buttons, this fixes the issue.

Can we have possibility to add a prop to react-scrollable-tabs to manage the type of arrow buttons? And set `type="button"` as default. Thanks

**Comment by Mood-al** [comment]
Hmmmm, what you could do is disable the navigation buttons and use custom ones with any style or any shape you would like as it is shown here in this example.

https://react-tabs-scrollable.vercel.app/demos#WithCustomNavBtns

**Comment by Mood-al** [comment]
Of course, I'm going to add this to the next version.

Feel free to ask or leave any feedback about the package.

Thank you. 
Mohamad.

**Comment by ahmedatadjust** [comment]
Sure, will do. 
Can you let me know when will you update be released? 
Thanks

**Comment by Mood-al** [comment]
Well, I can't do this at the right moment since I'm not having a stable life at the moment. 

Once I can settle down and have proper internet, surely i will add it and add new features to the package.

**Comment by Mood-al** [comment]
Please update the package to v2
