### ISSUE TITLE
Problems with typescript types

### ISSUE THREAD

**Issue by sofialancubaREDATLAS** [Mood-al/react-tabs-scrollable#13]
Hello, I am working with the typescript library and I found some errors to be able to modify, for example, the navigation buttons that do not support a JSX.Element. Also when I want to modify the active state of the tab it only supports a number. Could it be added so that it admits a string?

Based on this, could you add the following types?

```
rightBtnIcon?: React.FunctionComponent | string | JSX.Element;
leftBtnIcon?: React.FunctionComponent | string | JSX.Element;
activeTab: number | string;
onTabClick: (e: React.BaseSyntheticEvent, id: number | string) => void;
```

**Comment by Mood-al** [comment]
Hey, of course, thank you for giving me the types already 😅 

On the next alpha version, i will add them.

**Comment by ahmedatadjust** [comment]
Hello @Mood-al 

When will be next alpha version be released?

**Comment by Mood-al** [comment]
@sofialancubaREDATLAS  @ahmedatadjust  Hey, I just updated the package to 2.0.3-alpha adding the types and fixing some issues.
if you encountered any issues just open an issue with it!
