### ISSUE TITLE
SyntaxError: Named export 'Tabs' not found.

### ISSUE THREAD

**Issue by deflexable** [Mood-al/react-tabs-scrollable#16]
```js 
import { Tabs, Tab } from "react-tabs-scrollable";
```

is bring an error ``SyntaxError: Named export 'Tabs' not found. The requested module 'react-tabs-scrollable' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'react-tabs-scrollable';
const { Tabs } = pkg;``

but after changing it to
```js
 import pkg from "react-tabs-scrollable";
const { Tabs, Tab } = pkg;
```

it bring another error ``ERROR: No matching export in "node_modules/react-tabs-scrollable/dist/react-tabs-scrollable.es.js" for import "default"``

- package version is
"react-tabs-scrollable": "^2.0.5-alpha"

**Comment by Mood-al** [comment]
I will look it up, but for now you can use this `import Tabs from "react-tabs-scrollable/Tabs";`

**Comment by Mood-al** [comment]
> ```js
> import { Tabs, Tab } from "react-tabs-scrollable";
> ```
> 
> is bring an error ``SyntaxError: Named export 'Tabs' not found. The requested module 'react-tabs-scrollable' is a CommonJS module, which may not support all module.exports as named exports. CommonJS modules can always be imported via the default export, for example using:
> 
> import pkg from 'react-tabs-scrollable'; const { Tabs } = pkg;``
> 
> but after changing it to
> 
> ```js
>  import pkg from "react-tabs-scrollable";
> const { Tabs, Tab } = pkg;
> ```
> 
> it bring another error `ERROR: No matching export in "node_modules/react-tabs-scrollable/dist/react-tabs-scrollable.es.js" for import "default"`
> 
> * package version is
>   "react-tabs-scrollable": "^2.0.5-alpha"

I tested it and there is no issue in my code base you can see this example that i just created now to see if there was any issue!

https://codesandbox.io/s/react-tabs-scrollable-v2-example-s471xv?file=/src/App.js

**Comment by uraz** [comment]
This error occurs if your app is built on top of [Remix](https://remix.run)

**Comment by Mood-al** [comment]
I've published a new patch fixing this issue, please check it out.
