### ISSUE TITLE
Missing Declaration File

### ISSUE THREAD

**Issue by erdemdev** [Mood-al/react-tabs-scrollable#19]
When using the 'react-tabs-scrollable' npm package in my next 13 project, I encountered the following TypeScript error:

**Error TS7016** - Missing Declaration File: TypeScript couldn't find a declaration file for 'react-tabs-scrollable.' It implicitly assigned it the 'any' type. Types are available at 'c:/Users/{user_folder}/{project_folder}/node_modules/react-tabs-scrollable/dist/index.d.ts,' but TypeScript couldn't resolve them according to the package.json "exports."

Additional Information:

Package Version: **2.0.6**
TypeScript Version: **5.2.2**
Next.js Version: **13.5.4**
Node.js Version: **18.16.1**
Operating System: **win10**

We may need an update to 'react-tabs-scrollable' package.json or typings to resolve these TypeScript issues.

**Comment by Mood-al** [comment]
Hello, this needs invastigation on my side.
I will see if i can patch an update soon!

**Comment by DDeme** [comment]
Can you please fix this issue? It will be nice to have it typescript compatible.

**Comment by Mood-al** [comment]
I've published a new patch fixing this issue.
