### ISSUE TITLE
onTabClick Error

### ISSUE THREAD

**Issue by IbnDaanis** [Mood-al/react-tabs-scrollable#3]
Sometimes I get this error when clicking on a tab:

<img width="412" alt="Screenshot 2022-08-08 at 11 16 17" src="https://user-images.githubusercontent.com/72618814/183396031-af55584b-9ffe-4f86-9fb7-11d7967f62d5.png">

**Comment by Mood-al** [comment]
Can you reproduce the bug? 
Or show me how you are handling the state

**Comment by Mood-al** [comment]
By the way onTabClick and activeTab are mandatory props you have to pass them in order to make the component work and handle its state 
As i showed in the basic example in the docs

**Comment by IbnDaanis** [comment]
> By the way onTabClick and activeTab are mandatory props you have to pass them in order to make the component works and handles its state As i showed in the basic example in the docs

You should add TypeScript so it's easier for us to use it.

**Comment by Mood-al** [comment]
> > By the way onTabClick and activeTab are mandatory props you have to pass them in order to make the component works and handles its state As i showed in the basic example in the docs
> 
> You should add TypeScript so it's easier for us to use it.

True I'm thinking of that but for now i think the docs are enough 
I will add ts when i will add more breaking changes to it
