### ISSUE TITLE
Example with children

### ISSUE THREAD

**Issue by Valtory** [Mood-al/react-tabs-scrollable#4]
hi! I'm looking for an example using children for tabs, like a "tab panel" or something like that, I'm trying to match with children but I can't.
And I have an issue for view in mobile, when is less of 900px in screen, the tabs are small, instead of scroll with draggable.
thanks!

**Comment by Mood-al** [comment]
Hey 

About the tab panels i was thinking to add them in the next version but for now maybe i will add any example abour how to add them manually and matching their tab if you could provide me with an example so i can start with it. 
The tabs are focused more on navigation and this is the reason why i built them.

About on mobile can you reproduce a codesandbox? Or any thing so i can see the issue.

**Comment by Mood-al** [comment]
> hi! I'm looking for an example using children for tabs, like a "tab panel" or something like that, I'm trying to match with children but I can't. And I have an issue for view in mobile, when is less of 900px in screen, the tabs are small, instead of scroll with draggable. thanks!

Hey, I updated the demos and added tabs screens, I dont know if this is what u want but I hope this helps u.
u can check it out from here, it's the second example.
https://react-tabs-scrollable.vercel.app/demos#withTabScreens
