### ISSUE TITLE
Feature requests and/or external contributions

### ISSUE THREAD

**Issue by greg-a-smith** [Mood-al/react-tabs-scrollable#6]
Hello @Mood-al.

I’ve installed this package and have been working on trying to implement it in a React project that I’m working on.  Your demo pages are great and have all the functionality I am looking for and the library is nice and small.

In order to move forward adopting this, however, there are some additional enhancements I would need.  I’m curious if you’re open to feature requests, external contributions or if it would be better (and allowed) to fork the repo.  Things that I need in order to fully implement are:

- Support refs on the component(s)
- Additional props exposed that would allow me to override aria labels with translated text strings
- Other general prop spreading so I could pass any additional props (e.g. `data-*` or `aria-*` attributes to the different nodes)
- I would like the ability to eject from using its `rts*` CSS classname structure and just pass all my own classnames.  The reasoning being our need to support theming and also CSS modules.

There might be others as I haven’t done a deep dive into the components yet, but these are the ones I have noticed right away.  At this point, I am more trying to figure out if this library could be a go-forward strategy.  Thanks for your consideration!

**Comment by Mood-al** [comment]
PR and other contributions are open so feel free to add all the functionality you want to add to this package and push the changes so I can test and see them.

But what isn't allowed is forking the code and using it in another project under a different project name without installing react-tabs-scrollable!

**Comment by Mood-al** [comment]
Hey,

I'm working now on v2 of react-tabs-scrollable and I opened this discussion for any feature request, so if there any features you would like to see please comment there.
https://github.com/Mood-al/react-tabs-scrollable/discussions/11#discussion-5067141
