### ISSUE TITLE
Could not find a declaration file for module(Typescript incompatible) 

### ISSUE THREAD

**Issue by jasan-s** [Mood-al/react-tabs-scrollable#7]
typescript types missing

**Comment by jasan-s** [comment]
I may contribute to add the type declarations if I find the time. TS is very highly used these days so it may very useful

**Comment by Mood-al** [comment]
I know that and I was planning to rewrite the library again with TS and add a new API with many changes but I faced some issues with the library that I'm using to bundle and compile all the code they just deprecated it and there is no replacement for it as I know 😕

**Comment by Mood-al** [comment]
Hey,

I'm working now on v2 of react-tabs-scrollable and I opened this discussion for any feature request, so if there any features you would like to see please comment there.
https://github.com/Mood-al/react-tabs-scrollable/discussions/11#discussion-5067141
