### ISSUE TITLE
How to invoke nav actions using custom buttons? (Question)

### ISSUE THREAD

**Issue by jasan-s** [Mood-al/react-tabs-scrollable#8]
I am not using the css , instead stying my own. I'm unclear how I can invoke nav actions similar to example using the buttons I created. E.g left arrow scrolls the tabs to left and right arrow scrolls the tabs to the rights

**Comment by Mood-al** [comment]
First create a ref via useRef
And then pass it to action prop 

And by using this ref you can get the action functions like so 
ref.current.[the_name_of_function].

And there is codesandbox example you can see how ive done so

**Comment by jasan-s** [comment]
The code sandbox examples don't utilize ref to invoke left or right scroll programmatically. 

What is the function names that I should invoke for nav

**Comment by Mood-al** [comment]
Oh that's true i didn't add the example in react-tabs-scrollable i just added it in svelte-tabs-scrollable 

The function's names are
ref.current.onLeftBtnClick()
ref.current.onRightBtnClick()

**Comment by jasan-s** [comment]
code sandbox: https://s471xv.csb.app/

**Comment by Mood-al** [comment]
Please see this example.
https://codesandbox.io/s/react-tabs-scrollable-with-custom-navigation-buttons-us0ck9?file=/src/App.js

I think the issue you are facing is bcz of z-index and absolute layers not with the library
